# modules/xdr_orchestration/kickstarter.py
#
# The Kickstarter: the running LogSim console GENERATES a self-contained PowerShell
# one-shot that turns a bare Windows box into a preflight-green attack target — so
# there is no hand-editing on the box. The console bakes in what it already knows:
#   • its own IP/URL (to scope the WinRM firewall rule + set the phone-home URL),
#   • a scoped token (so the box can POST readiness back to /api/v1/attack/register),
#   • exactly the atomics the selected story needs (technique IDs → -GetPrereqs).
#
# What the generated script does (run once, elevated, on the box):
#   1. Enable/configure WinRM, firewall rule SCOPED to the console IP, and
#      LocalAccountTokenFilterPolicy=1 (local admin gets a full token remotely).
#   2. Install Invoke-AtomicRedTeam + atomics UNATTENDED (NuGet provider, trusted
#      PSGallery, powershell-yaml) — no approval prompts, so it also works over WinRM.
#   3. Verify the Cortex XDR agent (cyserver) is installed and Running.
#   4. Self-check (mirrors connection.preflight()) → clear PASS/FAIL.
#   5. Phone home readiness so the console's health tile can flip green on its own.
# Idempotent, ships with -Uninstall, watermarked. Lab-only, security-sensitive.

import json
import time
from typing import List, Optional

# Default reference-story atomics, used when the caller doesn't pass technique IDs.
DEFAULT_TECHNIQUES = ["T1082", "T1016", "T1033", "T1057", "T1547.001"]

# Token substitution (NOT str.format — PowerShell is full of { } and $).
_TEMPLATE = r'''#requires -Version 5.1
<#
  LogSim XDR Kickstarter  —  GENERATED by the LogSim console, do not hand-edit.
  Generated at : __GENERATED_AT__
  Console      : __CONSOLE_URL__   (WinRM access scoped to __CONSOLE_IP__)
  Target scope : this box only. LAB-ONLY, security-sensitive (installs offensive tooling).
  Run ELEVATED:  powershell -ExecutionPolicy Bypass -File .\logsim-kickstarter.ps1
  Rollback    :  ... -File .\logsim-kickstarter.ps1 -Uninstall
#>
param(
    [switch]$Uninstall,
    [switch]$NoPhoneHome
)
$ErrorActionPreference = 'Stop'
$ConsoleIP   = '__CONSOLE_IP__'
$ConsoleUrl  = '__CONSOLE_URL__'
$Token       = '__TOKEN__'
$Techniques  = @(__TECHNIQUES__)
$AtomicPsd1  = 'C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1'
$RegKeyPath  = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'

function Say($m,$c='Gray'){ Write-Host $m -ForegroundColor $c }

if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Say 'Must run elevated (Run as Administrator).' 'Red'; exit 1
}

# ── Uninstall / rollback ──────────────────────────────────────────────────────
if ($Uninstall) {
    Say '== LogSim Kickstarter — UNINSTALL ==' 'Cyan'
    try { Disable-PSRemoting -Force -ErrorAction SilentlyContinue } catch {}
    foreach ($n in @('LogSim WinRM (scoped)')) {
        Get-NetFirewallRule -DisplayName $n -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue
    }
    try { Remove-ItemProperty -Path $RegKeyPath -Name 'LocalAccountTokenFilterPolicy' -ErrorAction SilentlyContinue } catch {}
    if (Test-Path 'C:\AtomicRedTeam') {
        try { Remove-Item 'C:\AtomicRedTeam' -Recurse -Force -ErrorAction SilentlyContinue } catch {}
    }
    Say 'Rollback complete (WinRM disabled, firewall rule + token-filter policy + atomics removed).' 'Green'
    exit 0
}

Say '== LogSim XDR Kickstarter ==' 'Cyan'
Say ("Console {0}, WinRM scoped to {1}" -f $ConsoleUrl, $ConsoleIP) 'DarkGray'

# ── 1) WinRM, scoped firewall, local-admin token policy ───────────────────────
Say '[1/5] Enabling WinRM (scoped to the console)...' 'Yellow'
Enable-PSRemoting -Force -SkipNetworkProfileCheck | Out-Null
try {
    Set-NetFirewallRule -Name 'WINRM-HTTP-In-TCP' -RemoteAddress $ConsoleIP -ErrorAction Stop
} catch {
    if (-not (Get-NetFirewallRule -DisplayName 'LogSim WinRM (scoped)' -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -DisplayName 'LogSim WinRM (scoped)' -Direction Inbound -Protocol TCP `
            -LocalPort 5985 -RemoteAddress $ConsoleIP -Action Allow | Out-Null
    }
}
New-ItemProperty -Path $RegKeyPath -Name 'LocalAccountTokenFilterPolicy' -PropertyType DWord -Value 1 -Force | Out-Null

# ── 2) Atomic Red Team, unattended (no NuGet/PSGallery prompts) ───────────────
Say '[2/5] Installing Atomic Red Team (unattended)...' 'Yellow'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
$np = Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue
if (-not $np -or $np.Version -lt [version]'2.8.5.201') {
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ForceBootstrap -Scope AllUsers | Out-Null
}
if (-not (Get-PSRepository -Name PSGallery -ErrorAction SilentlyContinue)) { Register-PSRepository -Default -ErrorAction SilentlyContinue }
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
if (-not (Get-Module -ListAvailable -Name 'powershell-yaml')) {
    Install-Module -Name 'powershell-yaml' -Force -Scope AllUsers -AllowClobber | Out-Null
}
IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1')
Install-AtomicRedTeam -getAtomics -Force
if (Test-Path $AtomicPsd1) { Import-Module $AtomicPsd1 -Force -ErrorAction SilentlyContinue }
# Resolve exactly the prereqs the selected story's techniques need.
foreach ($t in $Techniques) {
    try { Invoke-AtomicTest $t -GetPrereqs -ErrorAction SilentlyContinue | Out-Null } catch {}
}

# ── 3) Verify the Cortex XDR agent ────────────────────────────────────────────
Say '[3/5] Verifying Cortex XDR agent (cyserver)...' 'Yellow'
$agent = (sc.exe query cyserver) 2>$null
$agentOk = ($agent -match 'RUNNING')
if ($agentOk) { Say '   cyserver RUNNING' 'Green' } else { Say '   cyserver NOT running/installed — no endpoint telemetry will be collected.' 'Red' }

# ── 4) Self-check (mirrors the console preflight) ─────────────────────────────
Say '[4/5] Self-check...' 'Yellow'
$winrmOk  = ((Get-Service WinRM).Status -eq 'Running')
$atomicOk = (Test-Path $AtomicPsd1)
$checks = [ordered]@{ winrm = $winrmOk; atomic = $atomicOk; cortex_agent = $agentOk }
$allOk  = $winrmOk -and $atomicOk -and $agentOk
foreach ($k in $checks.Keys) { Say ("   {0}: {1}" -f $k, ($(if($checks[$k]){'PASS'}else{'FAIL'}))) ($(if($checks[$k]){'Green'}else{'Red'})) }
Say ("   OVERALL: {0}" -f ($(if($allOk){'GREEN — ready to fire'}else{'RED'}))) ($(if($allOk){'Green'}else{'Red'}))

# ── 5) Phone home readiness ───────────────────────────────────────────────────
if (-not $NoPhoneHome -and $ConsoleUrl) {
    Say '[5/5] Reporting readiness to the console...' 'Yellow'
    $body = @{ hostname = $env:COMPUTERNAME; ip = (Get-NetIPAddress -AddressFamily IPv4 |
             Where-Object { $_.IPAddress -notlike '169.254.*' -and $_.IPAddress -ne '127.0.0.1' -and $_.PrefixOrigin -ne 'WellKnown' } |
             Select-Object -First 1 -ExpandProperty IPAddress); ready = $allOk; checks = $checks } | ConvertTo-Json -Compress
    try {
        Invoke-RestMethod -Method Post -Uri ("{0}/api/v1/attack/register" -f $ConsoleUrl.TrimEnd('/')) `
            -Headers @{ 'X-API-Key' = $Token } -ContentType 'application/json' -Body $body -TimeoutSec 15 | Out-Null
        Say '   readiness reported.' 'Green'
    } catch { Say ("   phone-home failed (non-fatal): {0}" -f $_.Exception.Message) 'DarkGray' }
} else { Say '[5/5] Phone-home skipped.' 'DarkGray' }

Say ("`nDone. {0}" -f ($(if($allOk){'Box is preflight-green.'}else{'Resolve the FAIL(s) above, then re-run (idempotent).'}))) 'Cyan'
'''


def render_kickstarter(*, console_url: str, console_ip: str, token: str = "",
                       technique_ids: Optional[List[str]] = None) -> str:
    """Render the one-shot .ps1 with the console's own values baked in.

    console_url : the base URL the box phones home to (e.g. http://192.168.0.45:5000)
    console_ip  : the WinRM client IP the box scopes its firewall rule to
    token       : scoped API token for the readiness phone-home (may be empty if
                  the console has no LOGSIM_API_KEY set)
    technique_ids: the story's technique IDs → only these prereqs get installed
    """
    techs = technique_ids or DEFAULT_TECHNIQUES
    techs_ps = ", ".join(f"'{t}'" for t in techs)
    out = _TEMPLATE
    out = out.replace("__GENERATED_AT__", time.strftime("%Y-%m-%dT%H:%M:%S%z") or time.strftime("%Y-%m-%dT%H:%M:%S"))
    out = out.replace("__CONSOLE_URL__", console_url or "")
    out = out.replace("__CONSOLE_IP__", console_ip or "")
    out = out.replace("__TOKEN__", (token or "").replace("'", "''"))
    out = out.replace("__TECHNIQUES__", techs_ps)
    return out
